# -*- coding: utf-8 -*-
"""5311422136_Abdulloh_Tugas Big Data 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w1Hzue_NZ_nuy1vtFCupJ6sCTDnjuK3J
"""

#mengimpor librarry yang dibuthkan
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

#untuk baca file xsv
df = pd.read_csv('car_purchasing.csv', encoding='ISO-8859-1')
df.head()

#menghapus kolom ynag tidak dibuthkan
df.drop(columns=['customer name', 'customer e-mail', 'country', 'gender'], inplace=True)

df.head()

# memeriksa info dataset
df.info()
# bemeriksa jumlah niai yang hilang (NaN)
df.isna().sum()

# Membuat plot scatter antara gaji tahunan dan hutang kartu kredit
plt.scatter(df['annual Salary'] , df['credit card debt'])
plt.xlabel('annual Salary')
plt.ylabel('credit card debt')
plt.title('the corr between credit card debt and annual Salary')

# Membuat plot pair untuk melihat hubungan antar fitur
sns.pairplot(df)

# Memisahkan fitur (X) dan target (y)
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

#Melakukan penskalaan fitur dan target menggunakan MinMaxScaler
scale = MinMaxScaler()
X = scale.fit_transform(X)
y = scale.fit_transform(y.values.reshape(-1, 1))

# Memisahkan data menjadi data latih dan data uji menggunakan train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)

# Memisahkan data menjadi data latih dan data uji menggunakan train_test_split
lreg = LinearRegression()
lreg.fit(X_train, y_train)
print('Train score', lreg.score(X_train, y_train))
print('Test score', lreg.score(X_test, y_test))

y_pred = lreg.predict(X_test)

# Membangun model ANN
ann = Sequential([Dense(32, activation="relu"),
                 Dense(1, activation='linear')])

ann.compile(optimizer='adam',
            loss='mean_squared_error',
            metrics=['mean_absolute_error'])

# Melatih model ANN
history = ann.fit(X_train, y_train, epochs=50, validation_split=0.2)

# Mendapatkan nilai loss dan akurasi selama pelatihan
tr_acc = history.history['mean_absolute_error']
tr_loss = history.history['loss']
val_acc = history.history['val_mean_absolute_error']
val_loss = history.history['val_loss']

# Mencari epoch dengan loss dan akurasi terbaik
index_loss = np.argmin(val_loss)
val_lowest = val_loss[index_loss]
index_acc = np.argmin(val_acc)
acc_highest = val_acc[index_acc]

# Membuat label untuk plot
Epochs = [i+1 for i in range(len(tr_acc))]
loss_label = f'best epoch= {str(index_loss + 1)}'
acc_label = f'best epoch= {str(index_acc + 1)}'

# Memvisualisasikan loss dan akurasi pelatihan dan validasi
plt.figure(figsize= (20, 8))
plt.style.use('fivethirtyeight')

plt.subplot(1, 2, 1)
plt.plot(Epochs, tr_loss, 'r', label= 'Training loss')
plt.plot(Epochs, val_loss, 'g', label= 'Validation loss')
plt.scatter(index_loss + 1, val_lowest, s= 150, c= 'blue', label= loss_label)
plt.title('Training and Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(Epochs, tr_acc, 'r', label= 'Training Accuracy')
plt.plot(Epochs, val_acc, 'g', label= 'Validation Accuracy')
plt.scatter(index_acc + 1 , acc_highest, s= 150, c= 'blue', label= acc_label)
plt.title('Training and Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

plt.tight_layout
plt.show()

# Memprediksi nilai baru menggunakan model ANN
ann_y_pred = ann.predict(X_test)

# Mengevaluasi kinerja model regresi linier menggunakan R2 score
r2 = r2_score(y_test, y_pred)
print('R2 score:', r2)

# Mengevaluasi kinerja model ANN
ann.evaluate(X_test, y_test)

# Contoh prediksi menggunakan model ANN
ann.predict([[40, 70000.500, 9550,534000]])

# Memvisualisasikan nilai aktual vs. nilai prediksi dari model regresi linier dan ANN
plt.figure(figsize=(10, 6))
plt.scatter(y_test, y_pred, label='Linear Regression')
plt.scatter(y_test, ann_y_pred, label='ANN')
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], linestyle='--', color='gray')
plt.xlabel('Actual Values')
plt.ylabel('Predicted Values')
plt.title('Predicted vs. Actual Values')
plt.legend()
plt.show()